### ISSUE TITLE
curious, does this wipe out/touch my old version of node?

### ISSUE THREAD

**Issue by ralyodio** [smockle/homebrew-iojs#2]

**Comment by bcomnes** [comment]
NVM will let you keep clean separate copies of node/iojs versions.  This formula conflicts with node so it will make you uninstall node first.

**Comment by smockle** [comment]
Hi @chovy, thanks for the question. @bcomnes is right—this formula is incompatible with node. Other keg-only formulas exist which install io.js without linking it (i.e. without overwriting node). [nvm](https://github.com/creationix/nvm) is the easiest way I’ve found so far to have multiple versions of io.js/node installed side-by-side.
