### ISSUE TITLE
Do you mind updating the iojs package version?

### ISSUE THREAD

**Issue by lifehome** [smockle/homebrew-iojs#6]
It's a little bit outdated.

**Comment by bcomnes** [comment]
We've been keeping https://github.com/aredridel/homebrew-iojs up to date.  @smockle we can get you on as a contributor if you are interested

**Comment by lifehome** [comment]
@bcomnes Sweet! and thanks ;)

**Comment by smockle** [comment]
@lifehome This tap is outdated—I added a note to the top of the README a while back about the official Homebrew formula, but I wasn't sure whether I should delete this repo (should I?).

io.js is available from [Homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/iojs.rb), [Homebrew Casks](https://github.com/caskroom/homebrew-cask/blob/master/Casks/iojs.rb), and an [io.js-maintained tap](https://github.com/aredridel/homebrew-iojs)—I'd recommend any of those.

Personally, now I use ([and occasionally contribute to](https://github.com/aredridel/homebrew-iojs/pull/7)) @aredridel's [tap](https://github.com/aredridel/homebrew-iojs). @bcomnes I would be interested in becoming a contributor! What is the process for that?

**Comment by bcomnes** [comment]
@smockle you're added!

**Comment by smockle** [comment]
@bcomnes Many thanks! I just got the email. :) Should I delete this repo, or put a better message at the top of the README?

**Comment by bcomnes** [comment]
ermmm.... I think homebrew has ways of depreciating. Let me ask around.
