### ISSUE TITLE
Error: Calling Resource#sha1 is disabled!

### ISSUE THREAD

**Issue by mondalani** [smockle/homebrew-iojs#7]
Hi,

I am getting this on `brew upgrade` - "Error: Calling Resource#sha1 is disabled!". Tried a couple of blog posts, didn't help. How do I fix it?

Thanks,
Ani

**Comment by smockle** [comment]
Hi @mondalani, I’m sorry you’re experiencing an error. Here is what I recommend—I hope this helps:

1. This tap is no longer maintained, so I recommend you run `brew untap smockle/homebrew-iojs`.

2. `io.js` itself is no longer maintained. From [the `io.js` website](https://iojs.org/en/): “There won't be any further io.js releases. All of the features in io.js are available in Node.js v4 and above.”

3. `node` v4.x is still supported, as that version was [the first long-term support (LTS) release](https://nodejs.org/en/blog/release/v4.2.0/). You can install `node` v4.x with brew by running `brew install node@4`. The Homebrew recipe for `node` v4.x [does not use SHA1](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@4.rb#L27), so you should stop getting the error you mentioned.

4. While `node` v4.x is supported, newer `node` releases are also available from the core Homebrew tap: `brew install node@6` will install the latest LTS release. `brew install node` will install the latest release.

**Comment by mondalani** [comment]
Thanks @smockle! It did not work well, I guess some broke, that I couldn't figure out but looks like uninstalling and reinstalling is working.

Ani
